# Generated by Django 4.2.10 on 2024-05-05 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('branch', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('githubURL', models.URLField()),
                ('group_members', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
