# Generated by Django 4.2.10 on 2024-04-22 05:51

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('university', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('linkedinURL', models.URLField()),
            ],
        ),
    ]
