# Generated by Django 4.2.10 on 2024-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('IT', 'IT'), ('COE', 'COE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('AI', 'AI'), ('Network', 'Network'), ('Security', 'Security'), ('Web Development', 'Web Development'), ('Robotics', 'Robotics')], max_length=50),
        ),
    ]
